### PR TITLE
Only add @canonical_cluster_id if not nil to commands and fix graph UI

### LINKED ISSUE #97: Use cluster config to provide optional cluster argument
See https://github.com/OSC/osc-systemstatus/pull/96/files#r527159296 and 

    @canonical_cluster_id = @cluster_id.to_s.partition('-').first

### PR DESCRIPTION
**Pull request by msquee**
**Overview:**
- Only add @canonical_cluster_id if not nil to commands.

This PR fixes #97.

We can convert some functions using `capture3` to `pipeline_rw` that results in cleaner code:
```ruby
args = []
args.push("--clusters=\"#{@canonical_cluster_id}\"") if defined?(@canonical_cluster_id)

Open3.pipeline_rw([sinfo_cmd, *args], "wc -l", "uniq", "grep gpu:", "egrep idle", "wc -l") {|i, o, wait_threads|
  puts o.read
}
```

Instead of how it's currently done:
```ruby
o, e, s = Open3.capture3("#{sinfo_cmd} #{ "--clusters=\"#{@canonical_cluster_id}\"" if defined?(@canonical_cluster_id) } -N -h -a --Format='nodehost,gres:#{gres_length}' | uniq | grep gpu: | wc -l")

if s.success?
  @available_gpu_nodes = o.to_i
else
  # Return stderr as error message
  @error_message = "An error occurred when retrieving available GPU nodes. Exit status #{s.exitstatus}: #{e.to_s}"
  0
end
```

It's not clear how to implement the same level of error checking though. Food for thought.

### CODE REVIEW

File: lib/slurm_squeue_client.rb [hunk 1]
```diff
@@ -59,8 +67,8 @@ def squeue_jobs_running
   def sinfo
     return @sinfo if defined?(@sinfo)
 
-    cmd = '/usr/bin/sinfo'
-    args = ["-a", "-h", "-o=\"%C/%A/%D\"", "--clusters=\"#{@canonical_cluster_id}\""]
+    args = ["-a", "-h", "-o=\"%C/%A/%D\""]
+    args.push("--clusters=\"#{@canonical_cluster_id}\"") if defined?(@canonical_cluster_id)
```
Comment (ericfranz) [inline lib/slurm_squeue_client.rb:71]: The `"--clusters=\"#{@canonical_cluster_id}\""` and `if defined?(@canonical_cluster_id)` is duplicated in multiple places. Might be more readable in one method:

```
def clusters_arg
  @clusters_arg ||= ( @canonical_cluster_id ? "--clusters=\"#{@canonical_cluster_id}\"" : ""
end
```

then

    args.push(clusters_arg) unless clusters_arg.blank?

and

    "#{sinfo_cmd} #{clusters_arg} -N -h -a ..."

Also, above addresses the issue that `@canonical_cluster_id` is always defined, so `if defined?(@canonical_cluster_id)` will always be true.

**Comment by ericfranz** [comment]
As for the comment on pipeline_rw vs capture3 for the long single string commands, another approach would be to do the parsing of the sinfo output in Ruby instead. For example gres length is currently calculated using:

     o, e, s = Open3.capture3("#{sinfo_cmd} #{ clusters_arg } -o '%G' | awk '{ print length }' | sort -n | tail -1")
     @gres_length = o.to_i

with Ruby that would be

     o, e, s = Open3.capture3("#{sinfo_cmd}  #{ clusters_arg } -o '%G'")
     @gres_length = o.lines.map(&:strip).map(&:length).max

And for 

    o, e, s = Open3.capture3("#{sinfo_cmd}  #{ clusters_arg } -N -h -a --Format='nodehost,gres:#{gres_length}' | uniq | grep gpu: | wc -l")
    @available_gpu_nodes = o.to_i

you might do something like

    o, e, s = Open3.capture3("#{sinfo_cmd}  #{ clusters_arg } -N -h -a --Format='nodehost,gres:#{gres_length}'")
    @available_gpu_nodes = o.lines.uniq.grep(/gpu:/).count
